
services:
  app:
    build:
      context: .
    image: orquestra_image
    container_name: orquestra_service
    env_file:
      - .env
    environment:
      DB_PROD_URL: ${DB_PROD_URL}
      DB_PROD_USERNAME: ${DB_PROD_USERNAME}
      DB_PROD_PASSWORD: ${DB_PROD_PASSWORD}
    ports:
      - "8080:8080"