spring:
  datasource:
    url: ${DB_PROD_URL}
    username: ${DB_PROD_USERNAME}
    password: ${DB_PROD_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10        # Número máximo de conexões simultâneas no pool
      minimum-idle: 2              # Número mínimo de conexões ociosas
      idle-timeout: 60000          # Tempo (em ms) para uma conexão ociosa ser fechada (60s)
      max-lifetime: 1800000        # Tempo máximo de vida de uma conexão (30 minutos)
      connection-timeout: 30000    # Tempo máximo de espera para obter uma conexão (30s)
      leak-detection-threshold: 20000  # Loga conexões que demoram mais de 20s (opcional, para debugar)
      auto-commit: true
      validation-timeout: 5000

      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        prepareThreshold: 0     # Desativa erro relacionado a prepared statement duplicado (se persistir)

  jpa:
    hibernate:
      ddl-auto: update  # Ou validate / none em produção, se preferir segurança
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
